package com.example.gzano.uniboors.Model

/**
 * Created by gzano on 30/10/2017.
 */
enum class Lessons {

    APPLICAZIONI_WEB, SVILUPPO_SISTEMI_SOFTWARE, SISTEMI_DISTRIBUITI, MACHINE_LEARNING, SISTEMI_INFORMATIVI, SICUREZZA_DELLE_RETI, LCMC, DATA_MINING;
}