package com.example.gzano.uniboors.Model

/**
 * Created by gzano on 30/10/2017.
 */
enum class Lessons {

    BIG_DATA,
    BUSINESS_INTELLIGENCE,
    SVILUPPO_SISTEMI_SOFTWARE,
    SISTEMI_DISTRIBUITI,
    MACHINE_LEARNING,
    SISTEMI_INFORMATIVI,
    NETS_SECURITY,
    PERVASIVE_COMPUTING,
    SISTEMI_INTELLIGENTI_ROBOTICI,
    SMART_CITY_TECNOLOGIE_MOBILI,
    SUPPORTO_ALLE_DECISIONI,
    APPLICAZIONI_WEB,
    DATA_MINING;
}